### PR TITLE
added retail-analytics page

### PR DESCRIPTION
**Pull request by alessialin**
Merge retail analytics solution accelerator branch with main gh-pages

### CODE REVIEW

**Comment by strobaek** [comment]
The variable "listLinksRelatedAccelerators" should contain links to the GitHub pages, not the GitHub repos.

**Review by strobaek — CHANGES_REQUESTED** [review]
The value in listLinksRelatedAccelerators should point to the GitHub pages, and not the GitHub repo, e.g. ["/anomaly-detection/"]

**Comment by alessialin** [comment]
@strobaek I have changed the link, please check. Thanks

**Review by strobaek — COMMENTED** [review]
Is this correct?
const linkContributingGuide = "https://github.com/microsoft/dstoolkit-mlops-base/blob/main/CONTRIBUTING.md";

**Review by strobaek — APPROVED** [review]

**Pull request merged**
